### ISSUE TITLE
Bug in creation of new sub article from article index view (release/1.5)

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/Goldencobra#106]
There is a bug with sub article creation in release/1.5.

<img width="1563" alt="bildschirmfoto 2017-10-17 um 11 36 13" src="https://user-images.githubusercontent.com/1942953/31657950-044a7506-b330-11e7-9caf-7c1389a1c839.png">

This code expects `params[:parent]` to be the parent article id.

https://github.com/ikuseiGmbH/Goldencobra/blob/588b9a4913bd0152fc8774b0081bd552bb2b92bc/admin/articles.rb#L347-L356

But in the index view the value is the slug of the article:
> https://www.liquid-city.de/admin/articles/new?parent=location

The link is created here:
https://github.com/ikuseiGmbH/Goldencobra/blob/588b9a4913bd0152fc8774b0081bd552bb2b92bc/admin/articles.rb#L144

I think in the past `new_admin_article_path(parent: article)` resolved to a link with the id and it just worked. Somewhen the method may have changed to give the slug instead.

**Comment by 5minpause** [comment]
>  ronachera self-assigned this 42 seconds ago

I love how this works 👯‍♂️
