### ISSUE TITLE
Show warning that `Goldencobra::Article` cannot be deleted if it has descendants

### ISSUE THREAD

**Issue by 5minpause** [ikuseiGmbH/Goldencobra#25]
Right now the user sees a 500 error page without a helpful error message.

One possible fix is to display a helpful error message.
The other solution might be that you don't see an option to delete an article like that in the first place.

**Comment by donni106** [comment]
Is there an batch action for deleting multiple articles?
If not, it could be a first step to disable the delete action (hide or deactivate it) if the article has descendants.

**Comment by donni106** [comment]
I never came back on this. Thanks @ronachera for working on this.
