### ISSUE TITLE
NoMethodError on php requests

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/Goldencobra#47]
Handle php requests on article controller.
For example: 
.../wp-login.php results in a NoMethodError (500 error).

> NoMethodError: To respond to a custom format, register it as a MIME type first: http://guides.rubyonrails.org/action_controller_overview.html#restful-downloads. If you meant to respond to a variant like :tablet or :phone, not a custom format, be sure to nest your variant response within a format response: format.html { |html| html.tablet { ... } }

**Comment by 5minpause** [comment]
Great, that you'll tackle that problem. It's been bugging me for quite some time now. Looking forward to your PR.
