### ISSUE TITLE
Extend fields to copy on "copy widget"

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/Goldencobra#50]
Widgets have the functionality to be duplicated for faster creation of similar contents.
The connection to articles will not be duplicated when using this.
It would be nice to extend the duplication with the connected articles of a widget.
As a result, the user does not need to select the same articles afterwards.

**Comment by 5minpause** [comment]
The feature is implemented here: https://github.com/ikuseiGmbH/Goldencobra/blob/master/admin/widgets.rb#L140

**Comment by 5minpause** [comment]
@ronachera perhaps something fr you?

**Comment by donni106** [comment]
With regarding this issue from the current perspective, I do not know if copying the connected articles is a good way. You want the widget's content for a new widget to change some small things or maybe only the position.
Or do you want to copy a widget to change something and have it on the same article. Both options are possible.
What if a widget is connected to 20 articles? If you copy the connections too but you do not want them, you have to uncheck all 20 articles manually.

So what do you think is the best approach?

@5minpause @ronachera @marcometz @pwilimzig

**Comment by ronachera** [comment]
I think widgets provide some sort of "functionality" that is independent from specific articles. Like you said, @donni106, what if a widget is connected to 20 articles? I think it would be easier to copy widgets without the articles and select the ones you need afterwards.
