### ISSUE TITLE
New feature with article_urls has bugs

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/Goldencobra#59]
The feature with the PR https://github.com/ikuseiGmbH/Goldencobra/pull/56 has bugs.
There is often missing the entry for created articles in the article_urls table.
The startpage does not render, if there is no / at the end in the article_urls table.
More tests needed.

**Comment by marcometz** [comment]
How do you get an entry in article_urls-table with no / at the end?
There is no manual Input possible, the entries are autogenerated as save_callback
