### ISSUE TITLE
Cache key too long

### ISSUE THREAD

**Issue by 5minpause** [ikuseiGmbH/Goldencobra#74]
`Errno::ENAMETOOLONG - File name too long @ rb_file_s_stat - /Users/holger/projects/ikusei/metropolis/tmp/cache/DA2/34C/articles%2F31%2F203%2F357%2F264%2F263%2F503%2F459%2F542%2F223%2F330%2F382%2F456%2F516%2F536%2F226%2F266%2F492%2F291%2F530%2F411%2F439%2F302%2F215%2F276%2F303%2F262%2F267%2F454%2F312%2F197%2F487%2F453%2F512%2F624%2F448%2F505%2F63/6%2F462%2F404%2F498%2F355%2F494%2F596%2F270%2F242%2F629%2F239%2F489%2F280%2F452%2F525%2F193%2F586%2F395%2F238%2F598%2F470%2F528%2F449%2F529%2F639%2F219%2F627%2F209%2F608%2F592%2F405%2F588%2F195%2F403%2F220%2F576%2F207%2F269%2F14/1%2F259%2F511%2F282%2F325%2F301%2F584%2F460%2F634%2F444%2F218%2F469%2F204%2F406%2F192%2F371%2F257%2F632%2F490%2F407%2F268%2F575%2F285%2F619%2F358%2F224%2F451%2F292%2F551%2F256%2F392%2F217%2F502%2F300%2F360%2F299%2F298%2F640%2F25/5%2F630%2F305%2F633%2F481%2F243%2F214%2F496%2F531%2F396%2F356%2F626%2F537%2F345%2F286%2F225%2F441%2F461%2F414%2F497%2F201%2F504%2F457%2F606%2F486%2F198%2F366%2F455%2F527%2F540%2F631%2F544%2F458%2F491%2F513%2F196%2F522%2F287%2F24/5%2F205%2F279%2F194%2F450%2F402%2F297%2F252%2F208%2F541%2F2017-01-23+16%3A11%3A09+%2B0100`

This error is generated in https://github.com/ikuseiGmbH/Goldencobra/blob/master/admin/articles.rb#L388. 
I don't yet know why it's so long as it's supposed to only contain numbers (ids and updated_at). We have to investigate.

Thise are the lines in question:

``` ruby
objects_for_cache_key = Goldencobra::Article.where(id: params[:root_id]).first.descendants.reorder(:url_name)
cache_key ||= ["articles", params[:root_id], objects_for_cache_key.map(&:id), objects_for_cache_key.maximum(:updated_at)]
```

```
[1] > Goldencobra::Article.where(id: 31).first.descendants.count
=> 159
```

**Comment by 5minpause** [comment]
Perhaps we could use the String#hash method to solve this:

```
$ ["articles", 31, objects_for_cache_key.map(&:id), objects_for_cache_key.maximum(:updated_at)].join("-")
=> "articles-31-141-192-193-194-195-196-197-198-201-203-204-205-207-208-209-214-215-217-218-219-220-223-224-225-226-238-239-242-243-245-252-255-256-257-259-262-263-264-266-267-268-269-270-276-279-280-282-285-286-287-291-292-297-298-299-300-301-302-303-305-312-325-330-345-355-356-357-358-360-366-371-382-392-395-396-402-403-404-405-406-407-411-414-439-441-444-448-449-450-451-452-453-454-455-456-457-458-459-460-461-462-469-470-481-486-487-489-490-491-492-494-496-497-498-502-503-504-505-511-512-513-516-522-525-527-528-529-530-531-536-537-540-541-542-544-551-575-576-584-586-588-592-596-598-606-608-619-624-626-627-629-630-631-632-633-634-636-639-640-2017-01-23 16:11:09 +0100"
$ ["articles", 31, objects_for_cache_key.map(&:id), objects_for_cache_key.maximum(:updated_at)].join("-").hash
=> 1016519945327749490

**Comment by donni106** [comment]
The built hash looks good. I also do not think this quoted information will result in problems in this case.

**Comment by 5minpause** [comment]
Any objections @marcometz ?
