### ISSUE TITLE
Geocode errors should not prevent articles from being saved/updated

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/Goldencobra#98]
Golden Cobra has the ability to add geocoding features to `Goldencobra::Article`s with `belongs_to :location, class_name: Goldencobra::Location`.

Golden Cobra uses:
http://www.rubygeocoder.com
https://github.com/alexreisner/geocoder

There is a bug when `Goldencobra::Article`s are saved or updated that an internal server error occurs, i.e. _Geocoder::OverQueryLimitError_

If a `Goldencobra::Location` produces errors, the `Goldencobra::Article` has to be saved or updated anyway.

**Comment by 5minpause** [comment]
Should I do this @donni106 or is someone else on this? What's the priority here?

**Comment by donni106** [comment]
I would love it if you can find a good solution.
